### PR TITLE
Doc improvements

### LINKED ISSUE #2: Document the setup and usage in README
It's probably also worth converting README to rst and including the contents as `long_description` in setup.py.

### LINKED ISSUE #7: Documentation issue: needed to enable Google+ APIs in developer console
Setup failed until I enabled "Google+ API" in the developer console for the App I created for SSO authentication.

By "failed", I mean that I'd receive an Internal Error after signing into Google and being redirected back to Sentry during the SSO *configuration* process. Digging into it showed that it was a 403 response to a request to the google plus address for getting user profile data.

Not sure if this is expected, but if it is, would be worth documenting it here.

### PR DESCRIPTION
**Pull request by meastman**
- Document requirement for 'Google+ API' to be enabled.
- Convert README to ReST and include in package `long_description`

Fixes #2 
Fixes #7

### CODE REVIEW

**Comment by meastman** [comment]
@streeter reviewable

**Comment by streeter** [comment]
lgtm

**Comment by meastman** [comment]
Thanks; mind merging this?

**Comment by streeter** [comment]
> Thanks; mind merging this?

Yep. Also added you to the repo.

**Pull request merged**
